version: '3.0'
services:
  main:
    image: alpha-core:latest
    build: .
    environment:
      - MYSQL_HOST=sql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=pwd
    ports:
      - "8100:8100"
      - "9090:9090"
      - "9100:9100"
    volumes:
      - .:/var/wow/
  sql:
    image: mariadb:10.5.9
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    ports:
      - "3306:3306"
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d/
      - ./etc/databases/:/etc/databases/